### ISSUE TITLE
Password becomes visible when clicking "copy to clipboard"

### ISSUE THREAD

**Issue by ionics** [passwordcockpit/passwordcockpit#11]
Description:
Password gets visible when clicking "copy to clipboard".
This is not how it should be.

Possible reason:
When clicking the "copy to clipboard" Button, Google Chrome automatically selects the illegible password and so the password does become visible.

Expected result:
Password still not visible on "copy to clipbloard". It should be possible to copy a password to clipboard without making it visible on the screen.

This happens in Midori,Firefox and Chrome...

Needs fix.
Thank you.

**Comment by thiagolazzarotto** [comment]
+1

**Comment by bu3tt1** [comment]
This error is no longer present with newer versions of browsers.
