### ISSUE TITLE
Bug in searching when password and username are not set

### ISSUE THREAD

**Issue by arcaste** [passwordcockpit/passwordcockpit#12]
Endpoint `/passwords?q=searchField`.

It returns 500 internal server error when searching a word that appears in a saved element which has no password or username.

**Comment by bu3tt1** [comment]
it seems that it is not related to username and password

**Comment by bu3tt1** [comment]
api/v1/passwords?q=string with development mode enabled return: The data to decrypt cannot be empty

**Comment by bu3tt1** [comment]
`{
    "exception": {
        "class": "Laminas\\Crypt\\Exception\\InvalidArgumentException",
        "code": 0,
        "message": "The data to decrypt cannot be empty",
        "file": "/var/www/html/vendor/laminas/laminas-crypt/src/BlockCipher.php",
        "line": 463,
        "trace": [
            {
                "file": "/var/www/html/src/Password/src/Api/V1/Facade/PasswordFacade.php",
                "line": 555,
                "function": "decrypt",
                "class": "Laminas\\Crypt\\BlockCipher",
                "type": "->",
                "args": [
                    ""
                ]
            },
            {
                "file": "/var/www/html/src/Password/src/Api/V1/Action/ListPasswordAction.php",
                "line": 130,
                "function": "decrypt",
                "class": "Password\\Api\\V1\\Facade\\PasswordFacade",
                "type": "->",
                "args": [
                    ""
                ]
            },
            {
                "file": "/var/www/html/vendor/laminas/laminas-stratigility/src/Middleware/RequestHandlerMiddleware.php",
                "line": 54,
                "function": "handle",
                "class": "Password\\Api\\V1\\Action\\ListPasswordAction",
                "type": "->",
                "args": [
                    {}
                ]
            },`
