### ISSUE TITLE
Mime type error when try upload files

### ISSUE THREAD

**Issue by Megyo86** [passwordcockpit/passwordcockpit#18]
Hello!
I installed the docker version of this application, everything is fine except of the file upload, when I try to attach any type of file to the password entry they get Mime type error message. I tried to modify the .htaccess file and added the requested types but does not impacted to the behaviour. Please help were I'm doing wrong.

Thanks a lot,
BR
Megyo

**Comment by bu3tt1** [comment]
Allow to configure by environment variables (docker) the allowed mime types

**Comment by bu3tt1** [comment]
Add a file with a mime type list.
Add the image attribute PASSWORDCOCKPIT_UPLOAD_MIMETYPES that accept a string with comma separated value, eg.: "pdf,zip"

**Comment by bu3tt1** [comment]
Add a config file with an array containing all existing mime types (eg. https://gist.github.com/egulhan/efd2125ac2017b42d159#file-mime-type-list-php)

In docker-compose allow configuring the enabled mime types comma separated:
PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES: pdf,zip,doc
This replaced in /passwordcockpit/backend/config/autoload/upload.global.php
