### ISSUE TITLE
No user name and password combination is recognized

### ISSUE THREAD

**Issue by KamikazeRaven** [passwordcockpit/passwordcockpit#3]
I installed passwordcockpit following the instruction on a LXC in a Proxmox hypervisor. However, neither "admin" "Admin123!" and "user" "User123!" grant me access to the service. Any combination of username and password will return the same "undifined error". Would anyone know what cause the problem?

**Comment by bu3tt1** [comment]
Hello,
normally if you do not define PASSWORDCOCKPIT_ADMIN_PASSWORD in docker-compose the user and password should be: admin:Admin123!

You tried to set PASSWORDCOCKPIT_ADMIN_PASSWORD?

Are you using via HTTP or HTTPS? If HTTPS, the certificate is valid? Can you inspect the network calls with Chrome?

**Comment by KamikazeRaven** [comment]
I did try to change it. I also tried to build the development version. Neither works. I copied the username and password from the git page, but still not able to login. It does not recognize any combination. I'm suspecting that the front end is not talking with the database.

**Comment by bu3tt1** [comment]
Are you using via HTTP or HTTPS? If HTTPS, the certificate is valid? Can you inspect the network calls with Chrome?

**Comment by bu3tt1** [comment]
Since it is a SPA if you use HTTPS the certificates must be valid or you must add a security exception to your browser.

**Comment by ionics** [comment]
@KamikazeRaven the reason i guess why its not working for you. Hostname of docker host must be equal to             PASSWORDCOCKPIT_BASEHOST: https://example.com:443

So hostname has to be "example.com" as well!

Than it will work 100%!
@bu3tt1 please ad this to the documentation in docker-compose.yml file.
Thank you.
