### ISSUE TITLE
Causes Swagger to append "http://" or "https://" to a base URL that already contains the network protocol

### ISSUE THREAD

**Issue by ajsween** [passwordcockpit/passwordcockpit#4]
https://github.com/passwordcockpit/passwordcockpit/blob/3635b37e2a8227c6afd8378c60f3721050d42413/docker/php7.3/apache/entrypoint.sh#L120

Below is an example of the curl generated by Swagger when attempting to test the REST API:

`curl -X GET "https://https://localhost/api/v1/folders" -H  "accept: application/json"`

The environment variable "PASSWORDCOCKPIT_BASEHOST" must have either "http://" or "https://" due to how its being used elsewhere in the entrypoint.sh script. However, since the variable is configured in Swagger.json and Swagger also appends a network protocol via a form selector, the network protocol ends up being included twice.

```
 "host": "https://localhost",
    "basePath": "/api",
    "schemes": [
        "http",
        "https"
    ]
```
Most likely need a separate environment variable for just the FQDN or IP address.

**Comment by bu3tt1** [comment]
The new Docker image is ready: passwordcockpit/passwordcockpit:1.2.1-php-7.3-apache
