### ISSUE TITLE
When changing a password id from the URL, the details of the searched password are shown, but the folder structure is the same as before

### ISSUE THREAD

**Issue by Al90ex** [passwordcockpit/passwordcockpit#52]

**Comment by bu3tt1** [comment]
The tree does not update when you change the password ID directly in the URL.

**Comment by bu3tt1** [comment]
When the path contains passwordId the frontend must calculate the correct folder and must modify the browser URL. If password does not exist it must give error as now: sorry-page

**Comment by samuelecavalleri** [comment]
Fixed in 1.2.0.dev
