### ISSUE TITLE
docker return 500 after successful login

### ISSUE THREAD

**Issue by Son-kun** [passwordcockpit/passwordcockpit#59]
Hi, after successful login in self-hosted app in docker I get error on every endpoint.

`{"title":"Internal Server Error","type":"https://httpstatus.es/500","status":500,"detail":"An unknown error occurred."}`

On local docker it's working good, but on server not. In logs I don't have any useful information, even after set dosplay_errors "On" in php.ini.

`[16/Mar/2023:11:34:50 +0000] "GET /api/v1/users/1/permissions HTTP/1.1" 500 506 "http://<hostname>/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"`

PASSWORDCOCKPIT_SSL is disable,
PASSWORDCOCKPIT_DEBUG is true,
PASSWORDCOCKPIT_AUTHENTICATION_TYPE is password,
PASSWORDCOCKPIT_BLOCK_CIPHER_KEY is supersecretkey,
PASSWORDCOCKPIT_AUTHENTICATION_SECRET_KEY is authenticationsecretkey.

I don't know where to search next...

**Comment by bu3tt1** [comment]
hello,
which version are you using (docker image)? 
We are working on the next version of passwordcockpit which should be released in the next few weeks.

**Comment by bu3tt1** [comment]
Does the problem still exist?

**Comment by Seb-sti1** [comment]
I have the same error for docker image version 1.3.3
