### ISSUE TITLE
Can´t upload attachments in zip format

### ISSUE THREAD

**Issue by geo2306** [passwordcockpit/passwordcockpit#76]
Receiving the following error trying to upload an attachement:

![error](https://github.com/passwordcockpit/passwordcockpit/assets/32169386/a6849beb-cc66-4aff-8c3e-93f04a054bf1)

The accepted files are:
![imagen](https://github.com/passwordcockpit/passwordcockpit/assets/32169386/0174f281-f709-4ed6-870a-c30b057d3806)

The same message error with pdf files.

**Comment by geo2306** [comment]
Hi, this is the output from the message error:
Undefined array key "application/x-zip-compressed"

**Comment by geo2306** [comment]
Hi @bu3tt1 I´m getting error message:
Undefined array key "application/x-zip-compressed"

**Comment by bu3tt1** [comment]
Hello,

the mimetype "application/x-zip-compressed" is deprecated.
Would it be possible to generate the ZIP through a newer application that then uses the correct mimetype?
To correct the problem yourself quickly you can mount and overwrite the file https://github.com/passwordcockpit/backend/blob/master/config/autoload/mimetypes.php and add the desired mimetype.
We plan to add the mimetype in the next version that is yet to be planned.

Best regards

**Comment by geo2306** [comment]
> Hello,
> 
> the mimetype "application/x-zip-compressed" is deprecated. Would it be possible to generate the ZIP through a newer application that then uses the correct mimetype? To correct the problem yourself quickly you can mount and overwrite the file https://github.com/passwordcockpit/backend/blob/master/config/autoload/mimetypes.php and add the desired mimetype. We plan to add the mimetype in the next version that is yet to be planned.
> 
> Best regards

Thanks @bu3tt1, wich program uses the correct mimetype? I tried using Winrar and 7zip, but with the same result, also I performed a research about this mimetype and I can´t find any clue, btw I tried to change the mimetypes.php file but the owner´s file is root, and i doesn't have this password.

**Comment by bu3tt1** [comment]
To add 'xzipcompressed'=>'application/x-zip-compressed' in https://github.com/passwordcockpit/backend/blob/master/config/autoload/mimetypes.php

**Comment by samuelecavalleri** [comment]
Opened a pull request to add this mimetype.

https://github.com/passwordcockpit/backend/pull/20

**Comment by bu3tt1** [comment]
With the version 1.3.4 you can use:

PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES : 'xzip'

**Comment by bu3tt1** [comment]
Version 1.3.4 image has been released.
Thank you for giving us feedback related to the mimetype problem.
