### ISSUE TITLE
Even the installation successed no view

### ISSUE THREAD

**Issue by codeparksoftware** [passwordcockpit/passwordcockpit#87]
Hi guys,
I tried to install with docker. Everything is ok.
Even still it works on localmachine and localhost, still it does not work from remote. : 192.168....:8080/login
I deployed it on a ubuntuserver on a virtual machine.
After running I can connect to server but web browser does not render anything.
I checked the page source it is completely same with working one.
But on my localpc is not being rendered.
Just empty page.
Is there any idea? 

The page source view and errors

<img width="740" alt="image" src="https://github.com/passwordcockpit/passwordcockpit/assets/14142585/70a97769-13ae-4b70-ac31-be0ed834b712">

**Comment by bu3tt1** [comment]
What does it mean: I tried to install with docker.
Are you using the image we published on dockerhub (passwordcockpit/passwordcockpit:1.3.5)?

**Comment by codeparksoftware** [comment]
yes I have used the docker-compose.yml file and install on ubuntu server. I tried to connect via web browser it did not work and gave me empty page. When I inspected page then I realized that the javascripts cannot be executed in somehow. So these are the helpful evidence for the developer.
however I still use same compose file, it is weird that it works on localhost. 
It seemed to me that is something related to https.(I am not sure)
Did you deploy the application via docker and connect from client on your side?

**Comment by bu3tt1** [comment]
Yes, we deploy the application via docker and connect from client.

It could be related to the fact that PASSWORDCOCKPIT_BASEHOST would not contain a valid domain and the port for HTTPS should be 443 and not 8080.

According to the documentation:
```
# Use with PASSWORDCOCKPIT_SSL: disable
PASSWORDCOCKPIT_BASEHOST: http://localhost:8080
# Use with PASSWORDCOCKPIT_SSL: enable
#PASSWORDCOCKPIT_BASEHOST: https://localhost:4343
```

`localhost` must be replaced by your own domain

What value does the variable PASSWORDCOCKPIT_BASEHOST have?

**Comment by bu3tt1** [comment]
Are you sure you are using version 1.3.5?

**Comment by codeparksoftware** [comment]
Yes I changed my domain with our internal ip address. I don't plan to use top domain for it. Is it possible to use just local ip address?
Since we want to use it just for admin password depot, no need to use a domain or sub domain

**Comment by DominicDetta** [comment]
It's not possible to use IP addresses except for 127.0.0.1 with the Content Security Policy enabled. See https://www.w3.org/TR/CSP3/#match-hosts and https://www.w3.org/TR/CSP3/#grammardef-self
