### ISSUE TITLE
Nog getting past the login page

### ISSUE THREAD

**Issue by heydenb** [passwordcockpit/passwordcockpit#88]
Latest version: 1.3.5

Just simple setup using password authentication and with the sample admin password.
When I login I get redirected to login again.
I am not entering the wrong pw because when I do that I get a wrong-pw message.

**Comment by heydenb** [comment]
after login, the browsers session storage contains this.
ember_simple_auth-session: {"authenticated":{}}

After some debugging I see that I get routed to folders but it redirects to login again.
The jwt token was delivered by /api/token-auth/ and it looks ok.

contents:
{
  "iat": 1711804531,
  "exp": 1711805431,
  "data": {
    "language": "it",
    "ldap": false,
    "change_password": false
  },
  "sub": 1
}

**Comment by bu3tt1** [comment]
Can you please send the docker-compose.yaml?

**Comment by heydenb** [comment]
[docker-compose.zip](https://github.com/passwordcockpit/passwordcockpit/files/14848129/docker-compose.zip)
I use a .env  file to fill out the parameters

looks like this:
MARIADB_HOST=my-ip
MARIADB_ROOT_PASSWORD=<root_pw>
MARIADB_USER=<user>
MARIADB_USER_PASSWORD=<password>

MARIADB_PERSISTENT_VOLUME=/home/me/.mariadb/pwcockpit-local

PWCOCKPIT_UPLOAD_VOLUME=/home/me/pwcockpit/file-upload
PWCOCKPIT_BLOCK_CIPHER_KEY=supersecretkey
PWCOCKPIT_AUTHENTICATION_SECRET_KEY=authenticationsecretkey
PWCOCKPIT_BASEHOST=http://localhost:8080
PWCOCKPIT_AUTHENTICATION_TYPE=password
PWCOCKPIT_SWAGGER=enable
PWCOCKPIT_SSL=disable
PWCOCKPIT_ADMIN_PASSWORD=Password123!

**Comment by bu3tt1** [comment]
I tried with your configuration and it works.
Can you ensure that in the browser you use http://localhost:8080 instead of http://127.0.0.1:8080?

**Comment by heydenb** [comment]
That is the case

**Comment by bu3tt1** [comment]
Does the issue remain open?
