### ISSUE TITLE
Updated EmberJS 5.4

### ISSUE THREAD

**Issue by bu3tt1** [passwordcockpit/passwordcockpit#91]

**Comment by Saeverin** [comment]
The update will be done in two stages. At first the project will be updated to Ember V4.12 and after that the project will be updated to Ember V5.4.

The Update to Ember V4.12 is almost done. The update is being worked on on the 1.4.0.dev-branch in the Frontend project.

**Comment by Saeverin** [comment]
The update has been made to Ember V5.8
