### ISSUE TITLE
Add json and yaml to mimetypes.php

### ISSUE THREAD

**Issue by bu3tt1** [passwordcockpit/passwordcockpit#93]
extensions:
- json (mimetypes: application/json and text/plain)
- ymal (mimetypes: application/yaml and text/plain)
- yml (mimetypes: application/yaml and text/plain)

**Comment by DominicDetta** [comment]
Right now there is now way to specify multiple mimetypes for the same extension. I added the extensions  in the file `config/autoload/mimetypes.php` with the usually correct mimetype specified.

**Comment by DominicDetta** [comment]
Some extensions like `yml` are detected as `text/plain` mimetype, to accept these files you are forced to add the `txt` extension in the environment variable `PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES `
