### ISSUE TITLE
During build docker image i am getting issue

### ISSUE THREAD

**Issue by vjoshi1990** [passwordcockpit/passwordcockpit#94]
ERROR: failed to solve: process "/bin/sh -c set -ex; mkdir -p /myapp/passwordcockpit; cd /myapp/passwordcockpit; git clone -v https://github.com/passwordcockpit/frontend.git /myapp/passwordcockpit; git checkout dev-1.2.0; git pull origin dev-1.2.0" did not complete successfully: exit code: 1

**Comment by bu3tt1** [comment]
Branch dev-1.2.0 no longer exists, for what reason do you want to download this branch?

**Comment by bu3tt1** [comment]
Does the issue remain open?
