### ISSUE TITLE
docker compose install blank page

### ISSUE THREAD

**Issue by Beelbrox** [passwordcockpit/passwordcockpit#95]
Hi!

i've installed it via docker-compose file and i try to reach the webpage (localhost:808) but  get only a blank page. 

I see that it has right permission issue, and that can be also the solution. 
Why can't it changing a rights within the container? 
[passwordcockpit.txt](https://github.com/passwordcockpit/passwordcockpit/files/15432161/passwordcockpit.txt)

**Comment by bu3tt1** [comment]
In the ULR I saw that the port is not correct (8080) but I don't think that is the error.

It could be a rights issue of the folder you want to bind. What are the folders that you want to bind? Do the rights match the container user?
Our image allows you to change the user that runs the service with APACHE_RUN_USER and APACHE_RUN_GROUP

**Comment by Beelbrox** [comment]
I do not want to bind any specific folder. I have simply issued the docker compose up command with your recommended yaml file. 
I removed the comment about APACHE_RUN_USER and APACHE_RUN_GROUP, same issue.

(Yeah, i misspelled the port in this thread)

**Comment by bu3tt1** [comment]
Could you send your docker-compose.yaml?

**Comment by Beelbrox** [comment]
[passwordcockpit.txt](https://github.com/passwordcockpit/passwordcockpit/files/15483793/passwordcockpit.txt)

Of course! (I could not attach yaml extension)

**Comment by Beelbrox** [comment]
Any update?

**Comment by bu3tt1** [comment]
Please try with the last version: 1.3.5

**Comment by bu3tt1** [comment]
Does the issue remain open?
