### ISSUE TITLE
Can't be run in Synology 7.2

### ISSUE THREAD

**Issue by VitaliyAT** [passwordcockpit/passwordcockpit#96]
Look like mariadb for Ubuntu not compartible with Synology Container Manager. 

Could you adoped or help run it?

**Comment by bu3tt1** [comment]
Is your problem related to MariaDB or Passwordcockpit?

**Comment by bu3tt1** [comment]
Does the issue remain open?

**Comment by AllenChioa** [comment]
i download  image 1.3.5 from Synology 7.2 Container Manager , using admin/Admin123! , can't login 
<img width="710" alt="Screenshot 2024-07-16 214345" src="https://github.com/user-attachments/assets/4065882d-015d-4169-a4bf-e40c462d032f">

**Comment by bu3tt1** [comment]
Your problem is not the same as : https://github.com/passwordcockpit/passwordcockpit/issues/3

**Comment by bu3tt1** [comment]
See also: https://github.com/passwordcockpit/passwordcockpit/issues/74 and https://github.com/passwordcockpit/passwordcockpit/issues/87

**Comment by bu3tt1** [comment]
Does the issue remain open?
